package streams

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"text/template"
	"time"
)

const (
	apiBase = "http://127.0.0.1:9997"

	defaultHLSAlwaysRemux           = false
	defaultHLSSegmentCount          = 3
	defaultHLSSegmentDuration       = 2 * time.Second
	defaultHLSPartDuration          = 200 * time.Millisecond
	defaultSourceOnDemand           = false
	defaultSourceOnDemandCloseAfter = 10 * time.Second
	defaultLogLevel                 = "warn"
	defaultRTSPTransport            = "tcp"
)

var (
	configTmpl = template.Must(template.New("mediamtx").Funcs(template.FuncMap{
		"yesNo": func(v bool) string {
			if v {
				return "yes"
			}
			return "no"
		},
	}).Parse(`# Generated by RTSPanda - do not edit manually

api: yes
apiAddress: 127.0.0.1:9997

metrics: yes
metricsAddress: 127.0.0.1:9998

hls: yes
hlsAddress: :8888
hlsAlwaysRemux: {{yesNo .Profile.HLSAlwaysRemux}}
hlsSegmentCount: {{.Profile.HLSSegmentCount}}
hlsSegmentDuration: {{.Profile.HLSSegmentDuration}}
hlsPartDuration: {{.Profile.HLSPartDuration}}

logLevel: {{.Profile.LogLevel}}

recordPath: {{.RecordDir}}/%path/%Y-%m-%d_%H-%M-%S
recordFormat: fmp4
recordSegmentDuration: 1h

paths:
{{- range .Cameras}}
  camera-{{.ID}}:
    source: {{.RTSPURL}}
    sourceOnDemand: {{yesNo $.Profile.SourceOnDemand}}
{{- if $.Profile.SourceOnDemand}}
    sourceOnDemandCloseAfter: {{$.Profile.SourceOnDemandCloseAfter}}
{{- end}}
    # Docker + some camera vendors can break UDP RTP delivery.
    # Transport is configurable for camera compatibility.
    rtspTransport: {{.Profile.RTSPTransport}}
    rtspAnyPort: yes
    record: {{if .RecordEnabled}}yes{{else}}no{{end}}
{{- end}}
`))

	profileOnce sync.Once
	profile     streamProfile
)

type configData struct {
	RecordDir string
	Cameras   []cameraEntry
	Profile   streamProfile
}

type cameraEntry struct {
	ID            string
	RTSPURL       string
	RecordEnabled bool
}

type streamProfile struct {
	HLSAlwaysRemux           bool
	HLSSegmentCount          int
	HLSSegmentDuration       time.Duration
	HLSPartDuration          time.Duration
	SourceOnDemand           bool
	SourceOnDemandCloseAfter time.Duration
	LogLevel                 string
	RTSPTransport            string
}

type proc struct {
	binPath    string
	configPath string
	recordDir  string
	mu         sync.Mutex
	cmd        *exec.Cmd
	cancel     context.CancelFunc
}

func (p *proc) writeConfig(cameras []cameraEntry) error {
	var buf bytes.Buffer
	data := configData{RecordDir: p.recordDir, Cameras: cameras, Profile: currentStreamProfile()}
	if err := configTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render config: %w", err)
	}
	if err := os.WriteFile(p.configPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// start launches mediamtx and returns a channel that receives when the process exits.
func (p *proc) start(parentCtx context.Context) (<-chan error, error) {
	p.mu.Lock()
	defer p.mu.Unlock()

	pctx, cancel := context.WithCancel(parentCtx)
	cmd := exec.CommandContext(pctx, p.binPath, p.configPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		cancel()
		return nil, fmt.Errorf("start mediamtx: %w", err)
	}

	p.cmd = cmd
	p.cancel = cancel

	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	return done, nil
}

// stop signals mediamtx to exit.
func (p *proc) stop() {
	p.mu.Lock()
	cmd := p.cmd
	cancel := p.cancel
	p.mu.Unlock()

	if cmd != nil && cmd.Process != nil {
		cmd.Process.Signal(os.Interrupt)
	}
	if cancel != nil {
		cancel()
	}
}

// waitForAPI polls the mediamtx API until it responds or ctx is cancelled.
func waitForAPI(ctx context.Context) {
	client := &http.Client{Timeout: 2 * time.Second}
	for {
		resp, err := client.Get(apiBase + "/v3/paths/list")
		if err == nil {
			resp.Body.Close()
			return
		}
		select {
		case <-ctx.Done():
			log.Printf("streams: mediamtx API did not become ready before shutdown (last error: %v)", err)
			return
		case <-time.After(250 * time.Millisecond):
		}
	}
}

func apiAddPath(e cameraEntry) error {
	cfg := currentStreamProfile()
	bodyData := map[string]any{
		"source":         e.RTSPURL,
		"sourceOnDemand": cfg.SourceOnDemand,
		"rtspTransport":  cfg.RTSPTransport,
		"rtspAnyPort":    true,
		"record":         e.RecordEnabled,
	}
	if cfg.SourceOnDemand {
		bodyData["sourceOnDemandCloseAfter"] = cfg.SourceOnDemandCloseAfter.String()
	}
	body, _ := json.Marshal(bodyData)
	return apiDo("POST", "/v3/config/paths/add/camera-"+e.ID, body)
}

func apiRemovePath(id string) error {
	return apiDo("DELETE", "/v3/config/paths/delete/camera-"+id, nil)
}

func apiDo(method, path string, body []byte) error {
	var bodyReader io.Reader
	if body != nil {
		bodyReader = bytes.NewReader(body)
	}
	req, err := http.NewRequest(method, apiBase+path, bodyReader)
	if err != nil {
		return err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		err := fmt.Errorf("mediamtx API %s %s: %d %s", method, path, resp.StatusCode, string(b))
		log.Printf("streams: mediamtx API error: %v", err)
		return err
	}
	return nil
}

func findBinary() (string, error) {
	if path := os.Getenv("MEDIAMTX_BIN"); path != "" {
		if _, err := os.Stat(path); err != nil {
			return "", fmt.Errorf("MEDIAMTX_BIN %q not found: %w", path, err)
		}
		return path, nil
	}

	name := "mediamtx"
	if runtime.GOOS == "windows" {
		name = "mediamtx.exe"
	}

	localPath := filepath.Join("mediamtx", name)
	if _, err := os.Stat(localPath); err == nil {
		abs, err := filepath.Abs(localPath)
		if err != nil {
			return localPath, nil
		}
		return abs, nil
	}

	if path, err := exec.LookPath("mediamtx"); err == nil {
		return path, nil
	}

	return "", fmt.Errorf("mediamtx binary not found — place it at %q or set MEDIAMTX_BIN", localPath)
}

func currentStreamProfile() streamProfile {
	profileOnce.Do(func() {
		profile = loadStreamProfile()
		log.Printf(
			"streams: mediamtx profile sourceOnDemand=%v closeAfter=%s hlsAlwaysRemux=%v segmentCount=%d segmentDuration=%s partDuration=%s logLevel=%s rtspTransport=%s",
			profile.SourceOnDemand,
			profile.SourceOnDemandCloseAfter,
			profile.HLSAlwaysRemux,
			profile.HLSSegmentCount,
			profile.HLSSegmentDuration,
			profile.HLSPartDuration,
			profile.LogLevel,
			profile.RTSPTransport,
		)
	})
	return profile
}

func loadStreamProfile() streamProfile {
	cfg := streamProfile{
		HLSAlwaysRemux:           envBool("MEDIAMTX_HLS_ALWAYS_REMUX", defaultHLSAlwaysRemux),
		HLSSegmentCount:          envInt("MEDIAMTX_HLS_SEGMENT_COUNT", defaultHLSSegmentCount, 2, 10),
		HLSSegmentDuration:       envDuration("MEDIAMTX_HLS_SEGMENT_DURATION", defaultHLSSegmentDuration, time.Second, 10*time.Second),
		HLSPartDuration:          envDuration("MEDIAMTX_HLS_PART_DURATION", defaultHLSPartDuration, 100*time.Millisecond, 2*time.Second),
		SourceOnDemand:           envBool("MEDIAMTX_SOURCE_ON_DEMAND", defaultSourceOnDemand),
		SourceOnDemandCloseAfter: envDuration("MEDIAMTX_SOURCE_ON_DEMAND_CLOSE_AFTER", defaultSourceOnDemandCloseAfter, time.Second, 5*time.Minute),
		LogLevel:                 envEnum("MEDIAMTX_LOG_LEVEL", defaultLogLevel, []string{"error", "warn", "info", "debug"}),
		RTSPTransport:            envEnum("MEDIAMTX_RTSP_TRANSPORT", defaultRTSPTransport, []string{"udp", "multicast", "tcp", "automatic"}),
	}

	if cfg.HLSPartDuration >= cfg.HLSSegmentDuration {
		log.Printf(
			"streams: MEDIAMTX_HLS_PART_DURATION (%s) must be lower than MEDIAMTX_HLS_SEGMENT_DURATION (%s); using default %s",
			cfg.HLSPartDuration,
			cfg.HLSSegmentDuration,
			defaultHLSPartDuration,
		)
		cfg.HLSPartDuration = defaultHLSPartDuration
	}

	return cfg
}

func envBool(name string, fallback bool) bool {
	v := strings.TrimSpace(os.Getenv(name))
	if v == "" {
		return fallback
	}
	parsed, err := strconv.ParseBool(v)
	if err != nil {
		log.Printf("streams: invalid %s=%q (expected true/false); using %v", name, v, fallback)
		return fallback
	}
	return parsed
}

func envInt(name string, fallback, min, max int) int {
	v := strings.TrimSpace(os.Getenv(name))
	if v == "" {
		return fallback
	}
	parsed, err := strconv.Atoi(v)
	if err != nil {
		log.Printf("streams: invalid %s=%q (expected integer); using %d", name, v, fallback)
		return fallback
	}
	if parsed < min || parsed > max {
		log.Printf("streams: invalid %s=%q (allowed range %d-%d); using %d", name, v, min, max, fallback)
		return fallback
	}
	return parsed
}

func envDuration(name string, fallback, min, max time.Duration) time.Duration {
	v := strings.TrimSpace(os.Getenv(name))
	if v == "" {
		return fallback
	}
	parsed, err := time.ParseDuration(v)
	if err != nil {
		log.Printf("streams: invalid %s=%q (expected Go duration like 2s or 200ms); using %s", name, v, fallback)
		return fallback
	}
	if parsed < min || parsed > max {
		log.Printf("streams: invalid %s=%q (allowed range %s-%s); using %s", name, v, min, max, fallback)
		return fallback
	}
	return parsed
}

func envEnum(name, fallback string, allowed []string) string {
	v := strings.ToLower(strings.TrimSpace(os.Getenv(name)))
	if v == "" {
		return fallback
	}
	for _, option := range allowed {
		if v == option {
			return v
		}
	}
	log.Printf("streams: invalid %s=%q (allowed: %s); using %q", name, v, strings.Join(allowed, ", "), fallback)
	return fallback
}
