package streams

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sync"
	"text/template"
	"time"
)

const (
	apiBase = "http://127.0.0.1:9997"
)

var configTmpl = template.Must(template.New("mediamtx").Parse(`# Generated by RTSPanda — do not edit manually

api: yes
apiAddress: 127.0.0.1:9997

hls: yes
hlsAddress: :8888
hlsAlwaysRemux: yes
hlsSegmentCount: 7
hlsSegmentDuration: 2s
hlsPartDuration: 200ms

logLevel: warn

recordPath: {{.RecordDir}}/%path/%Y-%m-%d_%H-%M-%S
recordFormat: fmp4
recordSegmentDuration: 1h

paths:
{{- range .Cameras}}
  camera-{{.ID}}:
    source: {{.RTSPURL}}
    sourceOnDemand: no
    # Docker + some camera vendors can break UDP RTP delivery.
    # Force TCP interleaved RTP for consistent connectivity.
    rtspTransport: tcp
    rtspAnyPort: yes
    record: {{if .RecordEnabled}}yes{{else}}no{{end}}
{{- end}}
`))

type configData struct {
	RecordDir string
	Cameras   []cameraEntry
}

type cameraEntry struct {
	ID            string
	RTSPURL       string
	RecordEnabled bool
}

type proc struct {
	binPath    string
	configPath string
	recordDir  string
	mu         sync.Mutex
	cmd        *exec.Cmd
	cancel     context.CancelFunc
}

func (p *proc) writeConfig(cameras []cameraEntry) error {
	var buf bytes.Buffer
	data := configData{RecordDir: p.recordDir, Cameras: cameras}
	if err := configTmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render config: %w", err)
	}
	if err := os.WriteFile(p.configPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// start launches mediamtx and returns a channel that receives when the process exits.
func (p *proc) start(parentCtx context.Context) (<-chan error, error) {
	p.mu.Lock()
	defer p.mu.Unlock()

	pctx, cancel := context.WithCancel(parentCtx)
	cmd := exec.CommandContext(pctx, p.binPath, p.configPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		cancel()
		return nil, fmt.Errorf("start mediamtx: %w", err)
	}

	p.cmd = cmd
	p.cancel = cancel

	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	return done, nil
}

// stop signals mediamtx to exit.
func (p *proc) stop() {
	p.mu.Lock()
	cmd := p.cmd
	cancel := p.cancel
	p.mu.Unlock()

	if cmd != nil && cmd.Process != nil {
		cmd.Process.Signal(os.Interrupt)
	}
	if cancel != nil {
		cancel()
	}
}

// waitForAPI polls the mediamtx API until it responds or ctx is cancelled.
func waitForAPI(ctx context.Context) {
	client := &http.Client{Timeout: 2 * time.Second}
	for {
		resp, err := client.Get(apiBase + "/v3/paths/list")
		if err == nil {
			resp.Body.Close()
			return
		}
		select {
		case <-ctx.Done():
			log.Printf("streams: mediamtx API did not become ready before shutdown (last error: %v)", err)
			return
		case <-time.After(250 * time.Millisecond):
		}
	}
}

func apiAddPath(e cameraEntry) error {
	body, _ := json.Marshal(map[string]any{
		"source":         e.RTSPURL,
		"sourceOnDemand": false,
		"rtspTransport":  "tcp",
		"rtspAnyPort":    true,
		"record":         e.RecordEnabled,
	})
	return apiDo("POST", "/v3/config/paths/add/camera-"+e.ID, body)
}

func apiRemovePath(id string) error {
	return apiDo("DELETE", "/v3/config/paths/delete/camera-"+id, nil)
}

func apiDo(method, path string, body []byte) error {
	var bodyReader io.Reader
	if body != nil {
		bodyReader = bytes.NewReader(body)
	}
	req, err := http.NewRequest(method, apiBase+path, bodyReader)
	if err != nil {
		return err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		b, _ := io.ReadAll(resp.Body)
		err := fmt.Errorf("mediamtx API %s %s: %d %s", method, path, resp.StatusCode, string(b))
		log.Printf("streams: mediamtx API error: %v", err)
		return err
	}
	return nil
}

func findBinary() (string, error) {
	if path := os.Getenv("MEDIAMTX_BIN"); path != "" {
		if _, err := os.Stat(path); err != nil {
			return "", fmt.Errorf("MEDIAMTX_BIN %q not found: %w", path, err)
		}
		return path, nil
	}

	name := "mediamtx"
	if runtime.GOOS == "windows" {
		name = "mediamtx.exe"
	}

	localPath := filepath.Join("mediamtx", name)
	if _, err := os.Stat(localPath); err == nil {
		abs, err := filepath.Abs(localPath)
		if err != nil {
			return localPath, nil
		}
		return abs, nil
	}

	if path, err := exec.LookPath("mediamtx"); err == nil {
		return path, nil
	}

	return "", fmt.Errorf("mediamtx binary not found — place it at %q or set MEDIAMTX_BIN", localPath)
}
